# Setup
title:               Curso ScadaBR 1.2
tagline:             'Por Celso Automação'
description:         'Curso completo e gratuito de ScadaBR em português.<br>Desenvolvido por <a href="https://celsoautomacao.com.br" target="_blank">Celso Automação</a>.'
url:                 'https://celsoautomacao.com.br'
baseurl:             '/curso-scadabr'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Celso Dell Anhol Ubaldo
  url:               https://celsoautomacao.com.br
  email:             celsoautomacao@outlook.com

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
